### ISSUE TITLE
Error "slow_conv2d_cpu" not implemented for 'Half'

### ISSUE THREAD

**Issue by arianaa30** [xinntao/Real-ESRGAN#710]
Having issues running the python script. Nothing is saved in `results` directory:

`python inference_realesrgan.py -n RealESRGAN_x4plus  -i inputs -s 4 -o results --face_enhance
`
```
Testing 6 children-alpha
Error "slow_conv2d_cpu" not implemented for 'Half'
If you encounter CUDA out of memory, try to set --tile with a smaller number.
```

**Comment by rkhyper** [comment]
Add --fp32

**Comment by arianaa30** [comment]
Cool, It makes it work for the first input image. But for the next one (00017_gray) it raises this error:

```
\anaconda3\Lib\site-packages\facexlib\utils\face_restoration_helper.py", line 355, in paste_faces_to_input_image
    upsample_img = inv_soft_mask * pasted_face + (1 - inv_soft_mask) * upsample_img
                                                 ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
ValueError: operands could not be broadcast together with shapes (1404,2000,1) (1404,2000)
```

Btw, why is it so slow? Much slower compared to the .exe counterpart.

**Comment by rkhyper** [comment]
I think the error is occured for face enhance (GFPGAN) , not for this model. Try removing this argument

**Comment by arianaa30** [comment]
Removed the face-enhance and now it works on the grayscale images. But for the video, still I get that error.
Video is actually more important for me. Not sure why it is happening.

**Comment by rkhyper** [comment]
Do you run inference_realesrgan.py or inference_realesrgan_video.py for video?

**Comment by arianaa30** [comment]
inference_realesrgan.py

**Comment by rkhyper** [comment]
You can try with inference_realesrgan_video.py

**Comment by arianaa30** [comment]
Ok. I tried this but it shows me an error:
`python inference_realesrgan_video.py -n RealESRGAN_x4plus -i inputs -s 4 --fp32 -o results`
Error:

```
realesrgan-ncnn-vulkan-20220424-windows\Real-ESRGAN-master\inference_realesrgan_video.py", line 296, in run
    pool = ctx.Pool(num_process)
           ^^^^^^^^^^^^^^^^^^^^^
  File "\AppData\Local\anaconda3\Lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\AppData\Local\anaconda3\Lib\multiprocessing\pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
```

**Comment by arianaa30** [comment]
Ok. I fixed it (my Torch was CPU and not GPU)!
Just wondering, is there a way to make it run faster? Does that .exe counterpart also works on video? I couldn't pass video to it.

**Comment by Dewey-Wang** [comment]
Hi, I would like to ask how did you change CPU to GPU?
